//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI4_WEBSERVICE.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public int idfuncionario { get; set; }
        public string matricula { get; set; }
        public int idusuario { get; set; }
        public string treinamento { get; set; }
        public int idsala { get; set; }
    }
}
