//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI4_WEBSERVICE.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        public int idsala { get; set; }
        public string nome { get; set; }
        public string numero { get; set; }
        public string andar { get; set; }
        public int idpredio { get; set; }
    }
}
